### ISSUE TITLE
Bug: Mishandling of missing values

### ISSUE THREAD

**Issue by akarlinsky** [cran/tabula#1]
Hi, thanks for a great package!

I encountered a bug with the way it handles missing values:

code to replicate error:
```
a <- c(1,1,NA,1)   
index_simpson(a)   
index_simpson(a, na.rm = T)   
```

Output (on both calls to `index_simpson`:
```
Error in if (!all(is_whole(x, ...))) { : 
  missing value where TRUE/FALSE needed
```

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
